volumes:
  scrumptious-mongo-data:
    external: true

services:
  fastapi:
    build:
      context: scrumptious_service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./scrumptious_service:/app
    environment:
      MONGO_URL: mongodb://admin_user:admin_password@mongo
      DATABASE_NAME: scrumptious-mongo-data
      WAIT_HOSTS: mongo:27017
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60  
      SIGNING_KEY: 87fe4a3fcfb60092dbaeb854a196bc3d9b190aed7930c734749e85245de698420c25f8e6899c421b4494e99459e01058de5daa9d49584cd62ec975da9aea33da

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SCRUMPTIOUS_SERVICE_API_HOST: http://localhost:8000

  mongo:
    image: mongo:6
    volumes:
      - scrumptious-mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: admin_password

  mongo-express:
    build:
      context: setup/mongo-express
      dockerfile: Dockerfile.dev
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin_password
      WAIT_HOSTS: mongo:27017
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
